### ISSUE TITLE
The reference to System.Commandline for Microsoft.TemplateEngine.Authoring.TemplateVerifier is invalid

### ISSUE THREAD

**Issue by vashdigital** [dotnet/templating#6226]
### Product

dotnet CLI & Visual Studio

### Describe The Bug

When I try to add the following package 
`Microsoft.TemplateEngine.Authoring.TemplateVerifier`
I get the following error
```
Error	NU1102	Unable to find package System.CommandLine with version (>= 2.0.0-beta4.22613.1)
  - Found 29 version(s) in nuget.org [ Nearest version: 2.0.0-beta4.22272.1 ]

```
Actually, the latest version of System.CommandLine is 2.0.0-beta4.22272.1 and I believe the version you use in the config is wrong.

### To Reproduce

Steps:
1. Make a MS Test project with .net 7
2. Try to add Microsoft.TemplateEngine.Authoring.TemplateVerifier as nugget package to the project
3. You get an error

### dotnet Info

<details>
  <summary>output</summary>
  
  
  
  
</details>

### Visual Studio Version

17.5.1

**Comment by YuliiaKovalova** [comment]
Hi @vashdigital ,

Thank you for reporting this issue. We are taking a look.

**Comment by YuliiaKovalova** [comment]
The issue was fixed in release/7.0.2xx .

Feel free to comment in the ticket if you have other questions.

**Comment by togglecode** [comment]
@YuliiaKovalova I still get the error installing the 7.0.201 version.

**Comment by YuliiaKovalova** [comment]
@togglecode , the fix will be available in release/7.0.202

**Comment by togglecode** [comment]
@YuliiaKovalova any idea, when it will be released?

**Comment by togglecode** [comment]
@YuliiaKovalova so is there no way meanwhile to use it? Any workarounds or alternatives?

**Comment by siyavash1984** [comment]
+1 to @togglecode , how we can workaround this issue?

**Comment by YuliiaKovalova** [comment]
@togglecode , @siyavash1984 
could you try to install the package from the feed <add key="dotnet-libraries" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json" />?

**Comment by vlada-shubina** [comment]
As a workaround, you can get the latest daily build of `Microsoft.TemplateEngine.Authoring.TemplateVerifier` from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json
(public feed) or connect to to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-libraries to restore missing System.CommandLine package.
